### ISSUE TITLE
Map Response JSON as Model Type

### ISSUE THREAD

**Issue by jonathan-casarrubias** [jonathan-casarrubias/loopback-sdk-builder#11]

**Comment by jonathan-casarrubias** [comment]
Not sure about this request, we really do need this??... by the moment a server response there are no types anymore.

**Comment by mevinDhun** [comment]
I believe this is a necessary feature. I have tried using the generated models but i discovered that json response can only be casted to the respective model. I added some custom methods to a model but the api returns only js objects.

For example, i have a User model with the following method:

```
isActive(){
	//custom business login
}
```

now when i do a find api call, i cannot call the above method since it does not exist on the "models" being returned. Mapping the json to the models would allow for class extensions and module augmentations. The following libraries can be helpful for the mapping:
[Automapper-ts](https://github.com/loedeman/AutoMapper)
[TypedJson] (https://github.com/JohnWhiteTB/TypedJSON)

Also, i could not find any relations in the generated models. Is that an intended feature?

**Comment by jonathan-casarrubias** [comment]
@mevinDhun the original purpose of this issue was to set the http call response to the model type, but since at the moment you get a response from the API -in your front end app- there is no such thing as types.

So, I'm trying to understand what you are saying, correct me if I get wrong:


What you are explaining is that at the moment you build the SDK you can not find custom remote methods you defined in loopback?

those are not part of the models but are part of the services, you can find any remote method -built in or custom- within the API Services, and not the models.

````js
constructor(private myServiceApi: <MyServiceApi>) {
  myServiceApi.customMethod().subscribe(); // this should work
}
````

So, again you won't find the remote methods if you create an instance of a model:

````js
private myModelInstance: <MyModel> = new MyModel();

constructor() {
  myModelInstance.customMethod().subscribe(); // this should not work
}
````

The only part that I think is missing within a model is to define the relations it may have, for example:


````js
private instance: <MyModel> = new MyModel();

constructor(private myServiceApi: <MyModelApi>) {
  myModelApi.findOne({
    include: 'someRelation'
  }).subscribe(instance: <MyServiceApi> => {
    this.instance = instance;
    console.log(this.instance.someRelation) // this won't work -I think it should-
    console.log(this.instance['someRelation']) // this work around does work.
  });
}

As you can see you still can use the relation datasets within a model with that TypeScript known work around, but is not the best way I expect to add the relations as optional parameters in the declaration files.

**Comment by mevinDhun** [comment]
Thanks for the quick reply. To clarify, i was talking about custom business logic which is needed only on the client side. The example i posted isActive() is a method which i want to create on the User model typescript file. Here is a sample of what i am trying to achieve:
```typescript
//User.ts
export class User implements UserInterface {
  public getFullname() {
      //this method is only to be used on the client side
     //does not exist on server
       return this.firstName + this.lastName;
    }
}

//home.component.ts
UserApi.findOne({})
.subscribe(fetchedUser: <UserInterface> => {
  	console.log(fetchedUser instanceof User); //false
        console.log(fetchedUser.getFullname()) // error- getFullname is not a function
  });
  ```
As you can see, all the business logic in my client models are unusable. Any work-around on how to get this to work? 
For the relations, is there any timeline on when it will be implemented. If this is not a priority, can you give me some heads up on how to modify the sdk-builder to generate the relations?

**Comment by jonathan-casarrubias** [comment]
@mevinDhun I understand now the issue;

I don't think is a good idea to directly modify the User.ts model within the generated file, because if you have updates in your API and re-generate the SDK you will lose your logic every time you follow the procedure.

Thinking in OOP extending the Model would be a better option.

Also, after your subscription you are defining the response type as UserInterface, but your logic is in the Model, so looks like a solution for that in typescript may be

````js
//home.component.ts
UserApi.findOne({})
.subscribe(fetchedUser: <User | UserInterface> => {
        console.log(fetchedUser.getFullname()) // should work 
  });
````

That supposing you will decide to keep adding logic to the User model, but if you rather decide to extend you could do something like:

````js

export class UserExtended extends User {
  public getFullname() {
       return this.firstName + this.lastName;
    }
}

//home.component.ts
UserApi.findOne({})
.subscribe(fetchedUser: <User | UserExtended | UserInterface> => {
        console.log(fetchedUser.getFullname()) // should work 
  });
````

Let me know if that is helpful or if you keep finding issues on this solution

**Comment by mevinDhun** [comment]
I tried using the UserExtended sample you posted, but i can't get it to compile. Type script complains:
**error TS1005: ',' expected.**

The error occurs on this line:
_fetchedUser: <UserExtended | UserInterface> =>_

It seems it does not understand the < x | x > syntax. Btw i am using latest typescript v1.8.

**Comment by jonathan-casarrubias** [comment]
ok my bad actually it should be between parenthesis

````js
//home.component.ts
UserApi.findOne({})
.subscribe((fetchedUser: <UserExtended | UserInterface>) => {
        console.log(fetchedUser.id) // should work thanks to interface
        console.log(fetchedUser.getFullname()) // should work thanks to extended model
  });
````

**Comment by mevinDhun** [comment]
it is not working, the error i get is: error _**TS2339: Property 'getFullname' does not exist on type 'FileExtended | FileInterface'.**_

i managed to map the json object to the user model using JSON.parse. Found it here:
[json to typescript](http://choly.ca/post/typescript-json/)

the code looks something like this:

```javascript

export class MobileUser implements MobileUserInterface {
     public getFullname() {
       return this.firstName + this.lastName;

    }

    // fromJSON is used to convert an serialized version
    // of the User to an instance of the class
    static fromJSON(json: MobileUserInterface | string): MobileUser {
        if (typeof json === 'string') {
            // if it's a string, parse it first
            return JSON.parse(json, MobileUser.reviver);
        } else {
            // create an instance of the User class
            let user = Object.create(MobileUser.prototype);
            // copy all the fields from the json object
            return Object.assign(user, json, {
                // convert fields that need converting
               //******need to treat relations******
            });
        }
    }

    // reviver can be passed as the second parameter to JSON.parse
    // to automatically call User.fromJSON on the resulting value.
    static reviver(key: string, value: any): any {
        return key === "" ? MobileUser.fromJSON(value) : value;
    }
 }

//UserApi.ts
public find(filter: LoopBackFilterInterface = undefined) {
    let method: string = "GET";
    let url: string = LoopBackConfig.getPath() + "/" + LoopBackConfig.getApiVersion() + "/mobileUsers";
    let urlParams: any = {
    };
    let params: any = {};
    if (filter) params.filter = filter;
    let result = this.request(method, url, urlParams, params);

    result.subscribe(users => {
      users.forEach(element => {
      let aUser: MobileUser = JSON.parse(JSON.stringify(element), MobileUser.reviver);
      aUser.getFullname(); //this works
       //some callback here
      });

    }, error => console.log('Could not load users.'),
      () => {});
   // return result;
  }

```

The downside is that it is not treating any relations. Also this requires modifying the generator. Maybe its best to include it in your generator so that it returns fully typed models.

**Comment by jonathan-casarrubias** [comment]
@mevinDhun yesterday I worked in a solution for this since I did find that the solution was incomplete.

I already have a good progress on this so the the API call will return an instance of the Model instead of the json.

There will remain the issue that after re-generating the SDK your changes in the model but I'm thinking in a solution for that.

Cheers!!
Jon

**Comment by jonathan-casarrubias** [comment]
@mevinDhun I have just published in beta17 the changes that implements this functionality. I have worked in an example using extended model.



Created a new `extended` folder within `shared` at the same level of  `sdk` and created course.extended.ts:
````js
import { Course } from '../../';

export class CourseExtended extends Course {
  constructor(json) { super(json); }

  test() {
    return `${this.name}: ${this.description}`;
  }
}
````

And then I implemented in the component as follows:

````js
import { Course, CourseApi, LoopBackConfig, CourseExtended } from './shared';

...

  constructor(private courseApi: CourseApi) {
    LoopBackConfig.setBaseURL('http://localhost:3000');
    LoopBackConfig.setApiVersion('api');
    courseApi.create({ 
      name: 'My Course',
      description: 'This is my super description'
    }).subscribe((course: Course) => {
      console.log(course);
      let courseExtended = new CourseExtended(course);
      console.log(courseExtended);
      console.log(courseExtended.test());
    });
  }
````

![image](https://cloud.githubusercontent.com/assets/1533239/16773701/7a648192-481e-11e6-90ed-459edd612758.png)

**Comment by jonathan-casarrubias** [comment]
@mevinDhun I have just published in beta17 the changes that implements this functionality. I have worked in an example using extended model.



Created a new `extended` folder within `shared` at the same level of  `sdk` and created course.extended.ts:
````js
import { Course } from '../../';

export class CourseExtended extends Course {
  constructor(json) { super(json); }

  test() {
    return `${this.name}: ${this.description}`;
  }
}
````

And then I implemented in the component as follows:

````js
import { Course, CourseApi, LoopBackConfig, CourseExtended } from './shared';

...

  constructor(private courseApi: CourseApi) {
    LoopBackConfig.setBaseURL('http://localhost:3000');
    LoopBackConfig.setApiVersion('api');
    courseApi.create({ 
      name: 'My Course',
      description: 'This is my super description'
    }).subscribe((course: Course) => {
      console.log(course);
      let courseExtended = new CourseExtended(course);
      console.log(courseExtended);
      console.log(courseExtended.test());
    });
  }
````

![image](https://cloud.githubusercontent.com/assets/1533239/16773701/7a648192-481e-11e6-90ed-459edd612758.png)

**Comment by mevinDhun** [comment]
Awesome. I tried it and it works. Thanks
