### ISSUE TITLE
Merge Angular2 with Nativescript2

### ISSUE THREAD

**Issue by JonnyBGod** [jonathan-casarrubias/loopback-sdk-builder#14]
Angular2 and Nativescript2 are integrating very well together and there are project trying to reuse most of the code for both platforms. (I am also working on such a starter)

Also looking to our current implementation it seams that both generators are very similar apart form two specific point:
- socket layer
- storage layer

I would consider trying to abstract both layers in a way that we could end up with only one template for both platforms.

Would like to know your thought on this.

**Comment by jonathan-casarrubias** [comment]
@JonnyBGod I also see we reuse most of the template components, the auth template is also different due the difference between the local storage implementation, but I already refactored the socket one to work as a common driver.

So, if we abstract a LocalStorage Driver like the Socket Driver I worked on, we may use the same auth component for both and then merge nativescript2 with angular2.

**Comment by JonnyBGod** [comment]
My goal here would be to check for the right driver to use at runtime. This way we could really merge into one library.

I will give it a go during the next few days.

**Comment by jonathan-casarrubias** [comment]
@JonnyBGod I'm not sure about that idea, because I want to keep the sdk generated size as small as possible, I was able to reduce it to 100kb (from > 500kb).... let the sdk to decide in runtime means that will need to carry the different drivers where ever you go.. Maybe for now it is not a big overhead , but then adding more drivers lately may increment the size.

If you can ensure we can keep around final 100kb per basic generated sdk then is ok.

Cheers
Jon

**Comment by JonnyBGod** [comment]
I agree that we should keep overhead as low as possible.

This is not a priority for me atm will look at it in the future but for now I am more concerned with tests and ngrx.

**Comment by jonathan-casarrubias** [comment]
Yes lets just keep the heavy lifting in the `loopback-sdk-builder` for now and keep the generated sdk as small as possible.

**Comment by jonathan-casarrubias** [comment]
I have merged the angular2 and nativescript generators, now they share the index.js.

Refactored the auth to support StorageDriver.

This was landed in beta9
