### ISSUE TITLE
Issue with referenced models on index.ts (angular2) - beta6

### ISSUE THREAD

**Issue by ottojimb** [jonathan-casarrubias/loopback-sdk-builder#17]
The file index.ts is generating:

`export * from './models';`
must be:
`export * from './services/models.service';`

And the "models.service.ts" requires be created.

Thank you!

**Comment by JonnyBGod** [comment]
There should not be a models.service. Models are just typed interfaces not services.

**Comment by jonathan-casarrubias** [comment]
Agree with @JonnyBGod these are different

**Comment by jonathan-casarrubias** [comment]
I'm re-opening just to verify there is actually no reference for the model.service -it should not-

**Comment by JonnyBGod** [comment]
@ottojimb is probably looking for some way to validate models at runtime. (connect me if I am wrong)

I believe this is out of scope for the project. But we can consider some kind of plugin system for these extensions.

**Comment by jonathan-casarrubias** [comment]
I'm still confused lol ... because at runtime there are no types, just plain javascript... @ottojimb can you clarify how you get to create this issue? thanks!!!

**Comment by ottojimb** [comment]
@JonnyBGod @jonathan-casarrubias I'm generating it with the "npm run build:sdk" and my generated index.ts is as follows: 

```
/* tslint:disable */
import { HTTP_PROVIDERS } from '@angular/http';
import { LoopBackAuth } from './services/auth.service';
import { ErrorHandler } from './services/errorHandler.service';
import { LoggerService } from './services/logger.service';
import { JSONSearchParams } from './services/search.params';
import {
  UserApi,
  AccessTokenApi,
  ...
  ReferenceApi,
  ValueApi,
  HolaApi
} from './services/api.service'
export const API_PROVIDERS: any[] = [
	HTTP_PROVIDERS,
	LoopBackAuth,
	ErrorHandler,
	LoggerService,
  JSONSearchParams,
  UserApi,
  AccessTokenApi,
  ...
  ReferenceApi,
  ValueApi,
  HolaApi
];
export * from './models'; //this line generates the issue
export * from './services/api.service';
export * from './services/config.service';
export * from './services/auth.service';
export * from './services/logger.config';
export * from './services/logger.service';
```

On google chrome dev tools I get: 

```
GET http://localhost:5555/app/shared/sdk/models.js 404 (Not Found)
Error: Error: XHR error (404 Not Found) loading http://localhost:5555/app/shared/sdk/models.js(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"
```

Then I replace the line with a new reference with the following content:

```
/* tslint:disable */

export * from '../models/User';
export * from '../models/AccessToken';
export * from '../models/ACL';
export * from '../models/RoleMapping';
export * from '../models/Role';
export * from '../models/ArticleType';
export * from '../models/Property';
export * from '../models/Option';
export * from '../models/OptionProperty';
export * from '../models/Country';
export * from '../models/State';
export * from '../models/City';
export * from '../models/Contact';
export * from '../models/Article';
export * from '../models/Image';
export * from '../models/Container';
export * from '../models/Group';
export * from '../models/Brand';
export * from '../models/Reference';
export * from '../models/Value';
export * from '../models/Hola';
```

Sorry by can't help, I'm newbie with git, the PR and typescript.

**Comment by jonathan-casarrubias** [comment]
I think we need to change that line for `models/index` Ill check tomorrow morning!!!

**Comment by ottojimb** [comment]
@jonathan-casarrubias 
Sorry, my VSCode hid the index file. Clearly it is the best solution.
Thank you!

**Comment by jonathan-casarrubias** [comment]
@ottojimb I just published beta8 with the modified line, I tested and worked.. 🎯 

Thanks for your patience!!!

Cheers,
Jon
