### ISSUE TITLE
generate local lb-ng blob

### ISSUE THREAD

**Issue by JonnyBGod** [jonathan-casarrubias/loopback-sdk-builder#2]
This should generate an executable in node_modules/.bin/lb-ng to prevent need for global installation and easy CI.

**Comment by jonathan-casarrubias** [comment]
Currently you can achieve that by doing the following

```sh
$ npm install --save-dev loopback-sdk-builder loopback-sdk-builder-cli
```

Then you can build an SDK as follows,

```sh
$ ./node_modules/.bin/lb-ng server/server.js path/to/client/sdk/index.ts -l [angular | angular2 | nativescript2] 
```

But I think is valuable to bundle everything in 1 package..

Lets see if others jump into this conversation and we may merge into 1 package if is better for the most.

Cheers
Jon!

**Comment by JonnyBGod** [comment]
Outdated since https://github.com/jonathan-casarrubias/loopback-sdk-builder/pull/3.

loopback-dk-builder-cli is no longer needed as this library ships with cli.
