### ISSUE TITLE
Provide config to decide which models generate

### ISSUE THREAD

**Issue by jonathan-casarrubias** [jonathan-casarrubias/loopback-sdk-builder#23]

**Comment by gvsdan** [comment]
Love you <3 i was about to open this issue.

**Comment by jonathan-casarrubias** [comment]
@gvsdan cool, I will be adding this feature in the following days.. Cheers!! Jon

**Comment by jonathan-casarrubias** [comment]
There is a new configuration available within any model.json

In order to disable a full model add the following configuration

````js
{
  "name": "Message",
  "plural": "messages",
  "base": "PersistedModel",
  "sdk": {
    "enabled": false // default is true
  }
}
````

If you want to disable specific methods only

````js
{
  "name": "Message",
  "plural": "messages",
  "base": "PersistedModel",
  "sdk": {
    "enabled": true,
    "blacklist": {
      "findOne": true // won't generate the findOne method
    }
  }
}
````

**Comment by jonathan-casarrubias** [comment]
Will be landed in beta12

**Comment by dmtw** [comment]
```
 "sdk": {
    "enabled": false
  }
```
 does not work with v2.1.0-rc2

**Comment by jonathan-casarrubias** [comment]
Hi @dmtw thanks for reaching out,

Hey so there are so many complications supporting 2 ways of avoiding the creation of models and I decided that I would support only 1, which is by using the default public property from model-config.json file

So, any model you don't want to create, just set public to false. This is a more robust implementation because it manage any issue when a model is public but a related model is private, it does the necessary to handle that kind of situations.

But you still can use the sdk setting to blacklist single methods

Cheers Jon
