### ISSUE TITLE
Add missing isAuthenticated method

### ISSUE THREAD

**Issue by jonathan-casarrubias** [jonathan-casarrubias/loopback-sdk-builder#34]

**Comment by cyberbobjr** [comment]
Hi, 
the isAuthenticated method is not complete, when you use it only check for getCurrentId is not null, but when you're looged out, the getCurrentId is an empty string.
Personnaly, i've replaced this :
`return this.getCurrentId() != null;`

by this :
`return !(this.getCurrentId() == null || this.getCurrentId() == "")`

**Comment by jonathan-casarrubias** [comment]
Hey @cyberbobjr 

Thank for reporting this, I will verify and push a fix for this ASAP..

Cheers!!!
@jonathan-casarrubias

**Comment by cyberbobjr** [comment]
Hello Jonathan,
some news :) after some tests, we noticed that the truly fix must be :
`
    return !(this.getCurrentId() == "" || this.getCurrentId() == null || this.getCurrentId() == "null");
`

it's really strange that the null variable must be quoted ?!?!

**Comment by jonathan-casarrubias** [comment]
@cyberbobjr wow that is strange, can you share your environment specs? since we use drivers and these behave different depending the environment.

Are you building a web or nativescript app?

**Comment by jonathan-casarrubias** [comment]
Fixed in Beta 18
