### ISSUE TITLE
Add unexpected ;

### ISSUE THREAD

**Issue by sirgalleto** [jonathan-casarrubias/loopback-sdk-builder#35]
In the beta15 version the created code have a error with unexpected ; in `LoopBackConfig.getApiVersion() + ;`

**Comment by jonathan-casarrubias** [comment]
@sirgalleto I have just pushed a fix in beta16 for this issue

**Comment by sirgalleto** [comment]
Thanks and congrats for this awesome project.

**Comment by jonathan-casarrubias** [comment]
🎉
