### ISSUE TITLE
Proposal: change in the linter pass

### ISSUE THREAD

**Issue by sirgalleto** [jonathan-casarrubias/loopback-sdk-builder#37]
Can you consider use `"eofline": true` in your tslint pass conditions?

I can add in a pull request the necesary changes.

**Comment by jonathan-casarrubias** [comment]
Sure, can you create a pull request for this?

**Comment by sirgalleto** [comment]
Yes, of course.

**Comment by gvsdan** [comment]
@jonathan-casarrubias I having an issue using my linter in some files generated by the builder for now i just trun off the `"eofline": true` but maybe we can do fix this in the tslint of the project.

**Comment by jonathan-casarrubias** [comment]
@gvsdan sure I will verify and send a fix for this ASAP.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
Ok I verified and it actually is on true, but there was a how fix in version 2.0.2 that introduced a lint issue I have fixed it and will be released in the next version.

**Comment by jonathan-casarrubias** [comment]
This issue is fixed on version 2.0.3

Jon

**Comment by gvsdan** [comment]
@jonathan-casarrubias  thanks dude <3

**Comment by sirgalleto** [comment]
Great!
