### ISSUE TITLE
base.service.ts json param handling issue: treats post json params to url params

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#52]
We have issues with custom end points that accept json param instead of data in body. Such params require to be transferred to the body for processing while sending in the request, and would not become part of the search/ url. So following assignment woudl never hit the API correctly:

```
      this.searchParams.setJSON(params);
      let request = new Request({
        headers : headers,
        method  : method,
        url     : requestUrl,
        search  : this.searchParams.getURLSearchParams(),
        body    : data ? JSON.stringify(data) : undefined
      });
```

params needs to be parsed and sent in the body I believe.

**Comment by sprypradeep** [comment]
Another good option here is not to make any changes in base.service but in the service method, we pass in params in place of the first param. as such end points do not have a separate data object.

but post params are not required to be injected in the search array.

**Comment by jonathan-casarrubias** [comment]
@sprypradeep  Could you please share just the configuration -not the logic- of your custom remoteMethod?

**Comment by jonathan-casarrubias** [comment]
never mind I was able to replicate and fix it.. will be released in RC5
