### ISSUE TITLE
custom methods with json params do not get appended to request body

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#53]
In the model function the "data" property is wrongly set from the first param (by ejs), this results in other params being missed, ideally we need to merge the params with data and send in request body:
```

    let result = this.request(method, url, urlParams, params<%= 
      postData && postData.length > 0 ? ", " + postData[0].arg : '' %>, true)<%

```
https://github.com/jonathan-casarrubias/loopback-sdk-builder/blob/master/lib/angular2/shared/services/custom/service.ejs#L194-L195

**Comment by sprypradeep** [comment]
we can just use the entire postData object and pass that on to "data",

**Comment by jonathan-casarrubias** [comment]
I think this is related to: https://github.com/jonathan-casarrubias/loopback-sdk-builder/issues/52

Please provide a custom remote method configuration as you are setting, so I can add it to the tests.

**Comment by jonathan-casarrubias** [comment]
never mind I was able to replicate and fix it.. will be released in RC5

**Comment by sprypradeep** [comment]
Thank you!
