### ISSUE TITLE
User.logout requires to be called twice to make returned observable to yield

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#58]
In a strange behavior, the UserApi.logout calls do not resolve in success callback getting invoked , when you do it first.

When you call it second time, it results in error as the token is absent now. And the .next gets called, and therefore the observable changes, and callback method is invoked.

This code works the first time as I called in .next on successful empty response as well), loopback does not return any response if logout is successful.
```
let logout: Subject<boolean> = new Subject<boolean>();
result.subscribe(() => {logout.next(true)}, () => logout.next(true));
return logout.asObservable();
```

**Comment by jonathan-casarrubias** [comment]
Fixed, will be launched in RC6
