### ISSUE TITLE
User.login  "Error: username or email is required"

### ISSUE THREAD

**Issue by Serranom4** [jonathan-casarrubias/loopback-sdk-builder#62]
The body of the request is : 
`{
      credentials: {
              email: "example@mail.com",
              password:"password"
      }
}`

instead of : 
`{
      email: "example@mail.com",
      password:"password"
}`

**Comment by jonathan-casarrubias** [comment]
Fixed, will be launched in RC6

**Comment by pmc-sstaehle** [comment]
Hey there, unfortunately I still got this error. My body looks like this:
`{email: 'test@mail.com', password: 'test'}`

I got follwing version installed: 
`FireLoop Version: 1.0.0-beta.2.6`
