### ISSUE TITLE
findById and find method in custom API - return type problem

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#63]
In the findById and find methods, the return type is being modified before returning:
findById
```
  public findById(id: any, filter: LoopBackFilter = undefined) {
...
    let result = this.request(method, url, routeParams, urlParams, postBody)
    return result.map((result: School | Array<School>) => Array.isArray(result)
                             ? result.map((instance: School)=> new School(instance))
                             : new School(result));
  }
```
find
```
  public find(filter: LoopBackFilter = undefined) {
...
    let result = this.request(method, url, routeParams, urlParams, postBody)
    return result.map((result: School | Array<School>) => Array.isArray(result)
                             ? result.map((instance: School)=> new School(instance))
                             : new School(result));
  }
```
Shouldnt they be returned as-is ? the find should result in an array always and never as a single Object, which creates problems with the caller, and also results in error on compilation. In case of findById, it can not be an array, so why are we introducing the check.

**Comment by jonathan-casarrubias** [comment]
Mapping the type of a result while fetching data is an expected behaviour that allows you to extend the SDK Models and add your own logic.

https://github.com/jonathan-casarrubias/loopback-sdk-builder/issues/11

Since all the methods are created in a loop of methods, fetch methods are added with this functionality and works standarazied -the same- in each of these methods, I may add logic while generating the sdk to avoid doing the check during API calls, but the functionality is expected and will remain.

Cheers
Jon

**Comment by sprypradeep** [comment]
Okay, so you are saying that the code for find() and findById() are coming from same template. The problem I face is the following compilation error (with ng serve / angular-cli)

```
Error: Typescript found the following errors:
  /home/XXX/tmp/broccoli_type_script_compiler-input_base_path-E2gLxjkB.tmp/0/src/app/XXX/school-list.component.ts (24, 18): Type 'School[] | School' is not assignable to type 'School[]'.
  Type 'School' is not assignable to type 'School[]'.
  /home/XXX/tmp/broccoli_type_script_compiler-input_base_path-E2gLxjkB.tmp/0/src/app/XXX/school-list.component.ts (24, 18): Type 'School[] | School' is not assignable to type 'School[]'.
  Type 'School' is not assignable to type 'School[]'.
    Property 'length' is missing in type 'School'.
```

with following component code

```
  **schools: School[];**

  constructor(
    private service: SchoolApi) {}

  ngOnInit() {
    this.service.find()
    .subscribe(
      schools => this.schools = schools,
      error =>  this.errorMessage = <any>error);
  }
```
Another error occurs on findById usage which includes message:

```
Type 'School[] | School' is not assignable to type 'School'.
  Type 'School[]' is not assignable to type 'School'.
    Property 'name' is missing in type 'School[]'.
```

**Comment by jonathan-casarrubias** [comment]
So, correct me if I'm wrong, but then you are receiving only 1 school in the call result?

````js
  ngOnInit() {
    this.service.find()
    .subscribe(
      schools => this.schools = schools,  // <----- HERE?
      error =>  this.errorMessage = <any>error);
  }
````

**Comment by sprypradeep** [comment]
Of course setting the type in response callback fixes the error. And Yes earlier also the result was in array for find() (thanks to Array.isArray), but wouldnt it be right if the two methods had different result dispensation.

**Comment by jonathan-casarrubias** [comment]
yes I just wanted to make sure that fixes your problem, but im keeping te issue open to handle find, findOne and findById while generating and not while excecuting

**Comment by jonathan-casarrubias** [comment]
Fixed, will be launched in RC6
