### ISSUE TITLE
Typescript lint error on "base.ejs"

### ISSUE THREAD

**Issue by ottojimb** [jonathan-casarrubias/loopback-sdk-builder#70]
On "lib/angular2/shared/services/core/base.ejs" the line 78 (rc6) must be: 

`let body: any; `

Actually it's generating "error TS7005: Variable 'body' implicitly has an 'any' type." on tslint.
Thank you!

**Comment by jonathan-casarrubias** [comment]
@ottojimb thank you for reporting.

This is issue is fixed and will be released in RC7
