### ISSUE TITLE
Autoreconnect bugfix

### ISSUE THREAD

**Issue by eggp** [jonathan-casarrubias/loopback-sdk-builder#71]
Hello!

(sry i little speak english)
When server restart, client reconnect is wrong ...

my bugfix generated socket.connections.ts:

https://gist.github.com/EggProject/32b463a98f94120c5962d68829ee7909

**Comment by jonathan-casarrubias** [comment]
@eggp thank you for reporting I will verify the issue and the patch and add it to the builder if valid.

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
Fixed, will be released in RC7
