### ISSUE TITLE
Duplicated function implementation 

### ISSUE THREAD

**Issue by sirgalleto** [jonathan-casarrubias/loopback-sdk-builder#75]
Actually I have a model with many duplicated function implementation with a little changes in tue URL endpoint.

![screen shot 2016-08-04 at 1 13 29 pm](https://cloud.githubusercontent.com/assets/5873627/17413102/7ff93f56-5a45-11e6-83dc-d1f94bd948bc.png)
![screen shot 2016-08-04 at 1 13 19 pm](https://cloud.githubusercontent.com/assets/5873627/17413101/7ff93768-5a45-11e6-903d-d0255268a737.png)
![screen shot 2016-08-04 at 1 13 10 pm](https://cloud.githubusercontent.com/assets/5873627/17413103/7ffa74fc-5a45-11e6-92dd-d619588749c2.png)

**Comment by jonathan-casarrubias** [comment]
Hi @sirgalleto that issue only happen in GlobalNotification Model?, can you share your GlobalNotification model properties and relations configuration.

Also, I see the function seems to be duplicated in more than 10 places? is that true? if so can you share the entire generated model? 

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
I'm sorry @sirgalleto  I have not been able to reproduce this issue and I already published this week release, if you can show your settings to be able to replicate this I will add it to a future release.

Cheers
Jon

**Comment by sirgalleto** [comment]
@jonathan-casarrubias Its working correctly in the last update. Good job 👍
