### ISSUE TITLE
RC7.2 reverses property optional? to required attributes

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#77]
In My model I have code and name as required, and other properties optional. The ? have been switched for them.

```
export interface BusinessInterface {
  brief: string;
  code?: string;
  detail: string;
  name?: string;
  type: string;
```

**Comment by jonathan-casarrubias** [comment]
ok then brief, detai and type should be the optionals?

**Comment by sprypradeep** [comment]
Yes, in the model I have code/ name as mandatory, others as optional.

**Comment by jonathan-casarrubias** [comment]
Fixed in RC8
