### ISSUE TITLE
2.0.0-rc.7.2 hasAndBelongsToMany nativescript wrong import

### ISSUE THREAD

**Issue by eggp** [jonathan-casarrubias/loopback-sdk-builder#79]
Hello!

my test loopback models:
https://gist.github.com/EggProject/b25c8ff85a5f881f65bd675fdbd5fac1

generate sdk: 
./node_modules/.bin/lb-sdk server/server.js PROJECTPATH/app/sdk -d nativescript2 -i enabled

sdk generator wrong service file generated when use hasAndBelongsToMany relation 

![image](https://cloud.githubusercontent.com/assets/1015211/17455814/1caa8646-5bc4-11e6-84a0-6aadaaa266a5.png)

i tested this bug with 2.0.0-rc.1 version is not detect this bug

**Comment by jonathan-casarrubias** [comment]
@eggp thanks for reporting I will verify and send a fix ASAP.

Cheers!
Jon

**Comment by jonathan-casarrubias** [comment]
Fixed in RC8
